name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest #設定server

    steps:
      - uses: actions/checkout@v3 # action獲得當下分支的source code
      - name: set up JDK 11 # set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew # shell command
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
